global using System;
global using Masuit.Tools;
global using Server.Application;
global using Server.Application.Entities;
global using Server.Core.Database;
global using Server.Domain.ApprovedPolicy;
global using Server.Domain.Basic;
global using Server.Domain.Repository;
global using Server.Entry.MiddleWares;
global using N_Doc = NPOI.XWPF.UserModel.XWPFDocument;
global using N_Par = NPOI.XWPF.UserModel.XWPFParagraph;
